### ISSUE TITLE
使用方法

### ISSUE THREAD

**Issue by starsky68** [xialuxi/yolov5_face_landmark#1]
请问，该开源是讲原yolov5中的对应文件替换，然后可以进行人脸关键点的训练？如果再加上口罩等其他类别，可行嘛，人脸关键点是相当于一个类？还是，如果需要集成到其他检测的话，需要分开进行，检测关键点的就检测关键点，检测其他的就检测其他的目标

**Comment by xialuxi** [comment]
原yolov5中的对应文件替换就行（数据读取部分要添加文件），人脸关键点是独立的，跟检测框同一个级别。需要增加口罩人脸的类别，直接增加类别就行，训练口罩人脸的关键点就添加关键点标签，不训练口罩人脸的关键点标签就给全部给-1就行。
