### ISSUE TITLE
预测相关

### ISSUE THREAD

**Issue by chenjianqiang199526** [xialuxi/yolov5_face_landmark#10]
大佬，预测的时候关键点*8-4是什么意思？

**Comment by chenjianqiang199526** [comment]
还有我看编码的时候并没有除宽高，只编码了偏移量，最后为什么预测的时候要乘以anchor的宽高

**Comment by cLEARLoVE00** [comment]
你好，想问下你知道怎么进行关键点的转换么？按照预测出来的关键点值在原图上画出的结果并不准确，想问下你知道怎么计算么？谢谢

**Comment by xialuxi** [comment]
相对网格的偏移量，参考anchor的中心点偏移量设计的，也可以自己调整。

**Comment by ggyybb** [comment]
> 相对网格的偏移量，参考anchor的中心点偏移量设计的，也可以自己调整。

我也觉得，v5是长宽×anchor，点回归没有，是不是关键点也不需要×anchor，作者是做了实验，结果效果不好么
