### ISSUE TITLE
关键点换算

### ISSUE THREAD

**Issue by cLEARLoVE00** [xialuxi/yolov5_face_landmark#12]
你好，我使用您提供的detect_one代码检测人脸和关键点，得到的关键点按照您的代码并没有得到相对应的坐标值，无法在原图上画关键点信息，想问下您是怎么得到图中的关键点结果的 @xialuxi

**Comment by xialuxi** [comment]
我的代码都测试过，没有问题的，你哪里运行有问题，直接提出来就行，如果是你自己的代码，那需要你自己调试。

**Comment by cLEARLoVE00** [comment]
用的是你的detect_one.py的代码,人脸框可以输出出来，但是关键点输出的结果不对，可不可以麻烦你测试一下关键点的输出结果，用你在git上的代码，谢谢了。有偿也可以

**Comment by cLEARLoVE00** [comment]
可不可以加个qq或者微信私聊一下，我这边对于yolov5训练人脸检测比较感兴趣，但是接触的比较少，缺少系统的方法，我的qq：1391570995，谢谢

**Comment by xialuxi** [comment]
可否贴出你的测试图片

**Comment by cLEARLoVE00** [comment]
![image](https://user-images.githubusercontent.com/38160563/114487138-a762a800-9c41-11eb-86d2-f656a73dec6e.png)
![image](https://user-images.githubusercontent.com/38160563/114487175-b8abb480-9c41-11eb-80d0-094ef1fa8792.png)
人脸框是正确的，关键点坐标不对，没法画出来

**Comment by xialuxi** [comment]
把原始网络预测的值打出来看下，要么测试下示例的图片。

**Comment by cLEARLoVE00** [comment]
![image](https://user-images.githubusercontent.com/38160563/114489158-3fae5c00-9c45-11eb-9f6e-107a72ab9326.png)
你的示例测试出来的结果，和你的一样么

**Comment by xialuxi** [comment]
那张图就是这个代码跑出来的，其他人测试都正常啊。。。。。
你这明显就是自己代码没有处理好，请检查scale_coords_landmarks里面的各项参数，代码级别的问题请自己认真调试。

**Comment by cLEARLoVE00** [comment]
主要是我没有任何操作代码，就是按照你的detect_one.py跑出来的结果，就是打印了结果，没有任何改动scale_coords_landmarks这个函数，但是画出来的关键点就是有问题的。会不会你本地上传的代码和这个不同呢，所以才想请你测试一下的

**Comment by xialuxi** [comment]
我大概知道你的问题了， 你的yolo.py文件没有替换。

**Comment by cLEARLoVE00** [comment]
谢谢，之前是这个文件没有替换
