### ISSUE TITLE
提问

### ISSUE THREAD

**Issue by T-SW** [xialuxi/yolov5_face_landmark#3]
请问框检测和关键点检测可否分开训练，有没有关键点数据格式样例，68关键点训练是否可行 @xialuxi

**Comment by xialuxi** [comment]
0 0.50146484375 0.2964860908105038 0.0361328125 0.0746705710189417 0.4964423828125 0.2896354319517268 0.51370703125 0.2896354319517268 0.50680078125 0.2981068814402679 0.4986396484375 0.31363689608336426 0.51370703125 0.3126954612369882
0 0.4150390625 0.332357247476466 0.037109375 0.07027818448841572 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
0 0.3271484375 0.3426061493810266 0.037109375 0.06149341142736375 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
0 0.234375 0.3616398243466392 0.037109375 0.06149341142736375 0.22659765625 0.34840995611669495 0.244384765625 0.34840995611669495 0.236275390625 0.3589985359129496 0.229212890625 0.37350951688096395 0.2425537109375 0.37390190341102425
0 0.0380859375 0.330161054211203 0.03125 0.05124450952280313 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
0 0.91748046875 0.2745241581578739 0.0400390625 0.06295754027087241 0.91109765625 0.26203953150927556 0.9289375 0.26244509519892745 0.920017578125 0.27662957543483935 0.912990234375 0.2887862372224918 0.92353125 0.28919180091214364
0 0.7841796875 0.2554904831922613 0.037109375 0.06588579795788974 0.7782509765625 0.24388140559208113 0.7955498046875 0.24220937045279425 0.7877373046875 0.25643191803863735 0.7782509765625 0.26814494878670664 0.7935966796875 0.26730746708821973
0 0.71630859375 0.3111273792455904 0.0380859375 0.06588579795788974 0.71044921875 0.29617276723799296 0.726353515625 0.29742752565687985 0.7190986328125 0.30830307470646223 0.712681640625 0.31876134703564457 0.72412109375 0.31918008788488805
0 0.595703125 0.29721815523225814 0.03125 0.05270863836631179 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
0 0.15869140625 0.338945827272255 0.0322265625 0.048316251835785806 -1 -1 -1 -1 -1 -1 -1 -1 -1 -1
