### ISSUE TITLE
landmark loss是增大的

### ISSUE THREAD

**Issue by starsky68** [xialuxi/yolov5_face_landmark#6]
![1611804969(1)](https://user-images.githubusercontent.com/31984917/106086462-2c6b1480-615d-11eb-8b1c-a6408e4bd829.png)
如上图所示，landmark的loss感觉不太正常，请问这是不是对的？

**Comment by xialuxi** [comment]
不好意思，完全看不到你发的图片。前面几次迭代关键点loss上涨是正常的，后面会趋于稳定下降。

**Comment by cLEARLoVE00** [comment]
你好，可以看一下你的训练标签么，想了解一下具体怎么做成训练的标签

**Comment by cLEARLoVE00** [comment]
> ![1611804969(1)](https://user-images.githubusercontent.com/31984917/106086462-2c6b1480-615d-11eb-8b1c-a6408e4bd829.png)
> 如上图所示，landmark的loss感觉不太正常，请问这是不是对的？
你好，想问下你在测试的时候回归的关键点结果准确么？我用的作者提供的detect_one.py文件得到的关键点结果映射到原图不正确，想问你是否有这种情况

**Comment by cLEARLoVE00** [comment]
你好，我想请教一下你的测试代码是如何修改的，我在训练过程中test的结果都是空的 @starsky68

**Comment by starsky68** [comment]
> 你好，我想请教一下你的测试代码是如何修改的，我在训练过程中test的结果都是空的 @starsky68

如果值为空，那就print你的每一步的输出结果，看一下是哪里除了问题

**Comment by cLEARLoVE00** [comment]
> > 你好，我想请教一下你的测试代码是如何修改的，我在训练过程中test的结果都是空的 @starsky68
> 
> 如果值为空，那就print你的每一步的输出结果，看一下是哪里除了问题
你好，想问下你训练的模型可以达到作者的训练精度么，我训练的模型在某些场景下没有作者的好，想问下你的效果怎么样
